<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

use App\Http\Controllers\AngularController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\CourseController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Any route beginning with /webcourses is answered with angular.blade.php, which
// is just a copy of the index.html generated by Angular compilation process.
Route::any('/{any}', [AngularController::class, 'index'])->where('any', '^(webcourses).*$');

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

// Jetstream user dashboard not part of the v4 group. Do not move it there.
Route::middleware(['auth:sanctum', 'verified'])->get('/user/dashboard', function () {
    return Inertia::render('Dashboard');
})->name('dashboard');

Route::group(['prefix' => 'v4'], function() {

    // Web courses directory / index
    Route::get('/courses', [CourseController::class, 'index']);

    // Paths grouped as /v4/user
    Route::group(['prefix' => 'user', 'auth:sanctum' => 'verified'], function() {

        // User profile
        Route::get('/', [UserController::class, 'loggedInUser']);

        // User's web courses
        Route::get('/courses', [CourseController::class, 'index']);
    });

});
