<?php

use Illuminate\Foundation\Application;
use Illuminate\Support\Facades\Route;
use Inertia\Inertia;

use App\Http\Controllers\AngularController;
use App\Http\Controllers\UserController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::any('/{any}', [AngularController::class, 'index'])
//   ->where('any', '^(?!api).*$')
// ;
// Route::any('/webcourse', [AngularController::class, 'index']);

// Any route beginning with /webcourses will answered with angular.blade.php, which
// is just a copy of the index.html generated by Angular compilation process.
Route::any('/{any}', [AngularController::class, 'index'])->where('any', '^(webcourses).*$');

Route::get('/', function () {
    return Inertia::render('Welcome', [
        'canLogin' => Route::has('login'),
        'canRegister' => Route::has('register'),
        'laravelVersion' => Application::VERSION,
        'phpVersion' => PHP_VERSION,
    ]);
});

Route::middleware(['auth:sanctum', 'verified'])->get('/user/dashboard', function () {
    return Inertia::render('Dashboard');
})->name('dashboard');

Route::get('/v4/user', [UserController::class, 'loggedInUser']);

// Route::middleware(['auth:sanctum', 'verified'])->any('/user/logout', function () {
//     route('logout');
// })->name('logout');
