name: Angular Compile

on: [ pull_request ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        
    - name: Install Angular 14.2.7
      uses: actions/angular-github-actions@14.2.7

    - name: Build
      run: |
        npm --prefix ./resources/webcourses run build
